name: Testing

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '5 1 * * *' # Run nightly
  workflow_dispatch:

jobs:
  testing:
    name: Astro build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 19.5.0

      - name: Run make clean
        run: make clean

      - name: Run make init
        run: make init

      - name: Run make build
        run: make build
